### ISSUE TITLE
"PHPUnit\TextUI\ResultPrinter" is internal and may change without further notice.

### ISSUE THREAD

**Issue by laceysanderson** [mheap/phpunit-github-actions-printer#26]
Hello, I Love this printer! We just recently updated to PHPUnit 8.5.13 and started receiving errors in our github actions due to your printer. You can see [here](https://github.com/tripal/t4d8/runs/1704123847?check_suite_focus=true) that the tests all pass beautifully using your printer with phpunit 7.5.10 but that the exact same tests on the same code show the following warning on the updated phpunit:

```
PHPUnit 8.5.13 by Sebastian Bergmann and contributors.

Testing 

Other deprecation notices (2)

  2x: The "PHPUnit\TextUI\ResultPrinter" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "mheap\GithubActionsReporter\Printer8".

Error: Process completed with exit code 1.
```

We are stuck with the updated phpunit version due to a dependency on Drupal for our project.

**Comment by mheap** [comment]
Hey @laceysanderson! It's been a while but I finally found time to sit down and investigate this. Whilst we do depend on an internal class, I'm not sure what the alternative is here.

I tried to reproduce your issue and the error shown isn't produced by the printer or by PHPUnit. I bootstrapped a test project with the following:

```
"require-dev": {
    "phpunit/phpunit": "8.5.13",
    "mheap/phpunit-github-actions-printer": "^1.5"
}
```

And when I ran the tests:

```
./vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer tests
PHPUnit 8.5.13 by Sebastian Bergmann and contributors.

::error file=tests/EmailTest.php,line=10::Failed asserting that 'Foo' is an instance of class "Email".
```

Are you running any static analysis tools that could be impacting the build?

**Comment by wdoug** [comment]
If I'm reading [this](https://github.com/sebastianbergmann/phpunit/issues/4024) correctly, it seems like there might have been an update so this is now an interface instead of a class that needs to be extended

**Comment by mheap** [comment]
I've just taken another pass at this and it looks as though it's to do with Symfony's PHPUnit bridge (thanks for the link @wdoug)!

Unfortunately in PHPUnit 8 I have to [extend](https://github.com/mheap/phpunit-github-actions-printer/blob/master/src/Printer8.php#L7) the `ResultPrinter` class even though it's internal

From [Sebastien](https://github.com/sebastianbergmann/phpunit/issues/4024#issuecomment-577013473):

> With that out of the way, yes, the fact that PHPUnit\TextUI\ResultPrinter is marked @internal is a problem. Its implementation is, and should stay, internal. However, for legacy reasons, it is also a public API as extending this class is an intended way for augmenting or changing the output printed by PHPUnit.

This issue was resolved by the addition of `DefaultResultPrinter` in PHPUnit 9, which this printer [extends](https://github.com/mheap/phpunit-github-actions-printer/blob/master/src/Printer9.php#L7).

I think the only solution here is to switch to PHPUnit 9, or run PHPUnit without using the Symfony bridge. In the mean time, I'll close and pin this issue in case it helps anyone else in the future
